#!/usr/bin/env bash
# Install Android SDK, NDK, platform-tools, and JDK for AeroDue (Pixel 8 / API 34).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ANDROID_DIR="$ROOT/android"

# Homebrew SDK root (android-commandlinetools cask)
if [[ -d /opt/homebrew/share/android-commandlinetools ]]; then
  export ANDROID_HOME="${ANDROID_HOME:-/opt/homebrew/share/android-commandlinetools}"
elif [[ -d "$HOME/Library/Android/sdk" ]]; then
  export ANDROID_HOME="${ANDROID_HOME:-$HOME/Library/Android/sdk}"
else
  export ANDROID_HOME="${ANDROID_HOME:-$HOME/Library/Android/sdk}"
fi

export ANDROID_SDK_ROOT="$ANDROID_HOME"
export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH"

echo "==> AeroDue Android toolchain setup"
echo "    ANDROID_HOME=$ANDROID_HOME"

need_brew() {
  if ! command -v brew >/dev/null 2>&1; then
    echo "Homebrew is required on macOS. Install from https://brew.sh" >&2
    exit 1
  fi
}

need_brew

if ! /usr/libexec/java_home -v 17 >/dev/null 2>&1; then
  echo "==> Installing Temurin JDK 17"
  brew install --cask temurin@17
fi
export JAVA_HOME="$(/usr/libexec/java_home -v 17)"
export PATH="$JAVA_HOME/bin:$PATH"
java -version

if ! command -v sdkmanager >/dev/null 2>&1; then
  echo "==> Installing Android command-line tools and platform-tools"
  brew install --cask android-commandlinetools android-platform-tools
fi

mkdir -p "$ANDROID_HOME/cmdline-tools"
if [[ ! -x "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" ]]; then
  echo "sdkmanager not found under $ANDROID_HOME/cmdline-tools/latest" >&2
  echo "Reinstall: brew reinstall android-commandlinetools" >&2
  exit 1
fi

echo "==> Accepting SDK licenses"
yes | sdkmanager --licenses >/dev/null || true

# Pixel 8: arm64-v8a, API 34; NDK for future llama.cpp / native inference
PACKAGES=(
  "platform-tools"
  "platforms;android-34"
  "build-tools;34.0.0"
  "ndk;26.1.10909125"
)
echo "==> Installing SDK packages: ${PACKAGES[*]}"
sdkmanager "${PACKAGES[@]}"

# Python venv for backend dev / parity tests (not bundled in APK)
PY311=""
for candidate in python3.11 /opt/homebrew/bin/python3.11; do
  if [[ -x "$candidate" ]]; then
    PY311="$candidate"
    break
  fi
done
if [[ -z "$PY311" ]]; then
  echo "==> Installing Python 3.11 (backend dev)"
  brew install python@3.11
  PY311="$(brew --prefix python@3.11)/bin/python3.11"
fi

if [[ ! -d "$ROOT/backend/.venv" ]]; then
  echo "==> Creating backend venv ($PY311)"
  "$PY311" -m venv "$ROOT/backend/.venv"
fi
# shellcheck source=/dev/null
source "$ROOT/backend/.venv/bin/activate"
pip install -q -U pip
pip install -q -e "$ROOT/backend[dev]"

LOCAL_PROPS="$ANDROID_DIR/local.properties"
cat >"$LOCAL_PROPS" <<EOF
# Generated by scripts/setup-android-env.sh — do not commit
sdk.dir=$ANDROID_HOME
EOF
echo "==> Wrote $LOCAL_PROPS"

# Gradle wrapper
if [[ ! -f "$ANDROID_DIR/gradlew" ]]; then
  echo "==> Generating Gradle wrapper"
  if ! command -v gradle >/dev/null 2>&1; then
    brew install gradle
  fi
  (cd "$ANDROID_DIR" && gradle wrapper --gradle-version=8.7)
fi

ENV_FILE="$ROOT/.env.android"
cat >"$ENV_FILE" <<EOF
# Source before Android builds: source .env.android
export ANDROID_HOME=$ANDROID_HOME
export ANDROID_SDK_ROOT=$ANDROID_HOME
export JAVA_HOME=$JAVA_HOME
export PATH=\$ANDROID_HOME/cmdline-tools/latest/bin:\$ANDROID_HOME/platform-tools:\$JAVA_HOME/bin:\$PATH
EOF
echo "==> Wrote $ENV_FILE (source before builds)"

echo ""
echo "Done. Next steps:"
echo "  source $ENV_FILE"
echo "  ./scripts/download-models.sh          # optional GGUF for on-device LLM"
echo "  cd android && ./gradlew :app:assembleDebug"
echo "  adb devices                         # connect Pixel 8 USB debugging"
